# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PetroProfile
                                 A QGIS plugin
 Constructs a graphical representation of drilling profiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-23
        copyright            : (C) 2019 by T-Systems on site service GmbH
        email                : gerrit.bette@t-systems.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PetroProfile class from file PetroProfile.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .petroProfile import PetroProfile
    return PetroProfile(iface)
